backend/version.go
build/darwin/info.plist
build/windows/Vegawallet.exe.manifest
build/windows/info.json
frontend/package.json
wails.json

Now the 0.1.0, we need to adjust the version to `0.2.0+dev`.

Set version to 0.2.0+dev

---

backend/config/config.go
backend/config/loader.go
backend/handler.go
frontend/src/types/handler.ts
frontend/src/wailsjs/go/models.ts

Add backend to support opting out the telemetry

---

frontend/automation/cypress/support/pages/network-drawer-page.js
frontend/src/components/network-info/network-info.tsx

Small change to existing assertions to include the console missing change when switching network to mainnet1
Closes 217

Add to method to check for console missing url change

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/network-config-container/network-config-container.tsx
frontend/src/components/onboard/onboard.tsx
frontend/src/components/transaction-manager/transaction-manager.tsx
frontend/src/contexts/global/global-actions.ts
frontend/src/contexts/network/network-actions.ts
frontend/src/hooks/use-create-wallet.tsx
frontend/src/hooks/use-import-network.tsx
frontend/src/hooks/use-import-wallet.tsx
frontend/src/lib/logging.ts

- Adds a logging module using [loglevel](https://www.npmjs.com/package/loglevel).
- Using logger.error will capture an error in Sentry
- Using logger.debug will add a breadcrumb in Sentry
- Using logger.info will capture a message in Sentry
- Adds a capture message for when users use a non default vega home.

feat: better fe logging

---

frontend/automation/cypress/integration/transaction-approval.feature
frontend/automation/cypress/support/step_definitions/transaction-approval.step.js
frontend/automation/package.json

Small change to fix tests failing locally and some BDD step changes
Closes #430

test: fix test running locally and BDD

---

CHANGELOG.md
backend/tx.go
frontend/src/components/key-value-table/key-value-table.tsx
frontend/src/components/transaction-manager/transaction-manager.tsx
frontend/src/components/transaction-manager/transaction-types.ts
frontend/src/components/transaction-modal/transaction-modal.tsx
frontend/src/lib/events.ts

Ensure transaction doesn't get serialized when nil in sent transaction event

---

CHANGELOG.md
frontend/src/components/dialog/dialog.tsx
frontend/src/components/key-value-table/key-value-table.tsx
frontend/src/components/transaction-modal/transaction-modal.tsx
main.go

Better sized transaction review window

---

CHANGELOG.md
backend/errors.go
backend/service.go
backend/service/state.go
backend/tx.go
frontend/src/components/transaction-manager/transaction-manager.tsx
frontend/src/lib/events.ts
frontend/src/wailsjs/go/backend/Handler.d.ts
frontend/src/wailsjs/go/backend/Handler.js
frontend/src/wailsjs/go/models.ts
frontend/src/wallet-client/interactions.ts
go.mod
go.sum

Support Wallet Service API version 2

---

frontend/automation/cypress/e2e/import-wallet.cy.js
frontend/automation/cypress/e2e/network-configuration.cy.js
frontend/automation/cypress/e2e/onboarding.cy.js
frontend/automation/cypress/e2e/wallet-service.cy.js
frontend/automation/cypress/e2e/wallets.cy.js
frontend/automation/cypress/support/commands.js

- Remove hardcoded waits, and duplicate visits.

test: improve flake

---

CHANGELOG.md
backend/config/config.go
backend/config/loader.go
backend/handler.go
main.go

Fix application crasher when not initialized

---

frontend/automation/cypress/e2e/network-configuration.cy.js
frontend/src/contexts/global/global-actions.ts

Fix/315: Restart service on network change

---

frontend/src/app.tsx
frontend/src/components/button/button.tsx
frontend/src/components/transaction-details/transaction-details.tsx
frontend/src/components/transaction-history/transaction-history.tsx
frontend/src/components/transaction-history/transaction-item.tsx
frontend/src/contexts/global/global-actions.ts
frontend/src/hooks/use-explorer-url.tsx
frontend/src/hooks/use-import-network.tsx
frontend/src/lib/networks.ts
frontend/src/routes/wallet/keypair/transactions.tsx
frontend/src/styles/_reset.css

Feat/388: Block explorer links

---

frontend/src/components/network-switcher/network-switcher.tsx
frontend/src/routes/wallet/home.tsx

- close network switch warning after confirming 
- add underline for wallet tabs

fix: minor visual / ux tweaks

---

frontend/automation/cypress/e2e/network-configuration.cy.js
frontend/automation/cypress/e2e/wallet-service.cy.js
frontend/src/contexts/global/global-reducer.ts

Fix/398: Open wallet on connection approval

---

frontend/src/components/connection-list/connection-manage-section.tsx
frontend/src/components/sign-message-dialog/sign-message-dialog.tsx

Closes #376 
- fixes resetting the message field on sign message
- fixes double headline for permissions dialog

Visual fixes

---

frontend/automation/cypress/e2e/wallet-connection.cy.js
go.mod
go.sum

chore: bump vega version

---

CHANGELOG.md
README.md
frontend/src/wailsjs/runtime/runtime.d.ts
go.mod
go.sum
main.go

Update to wails v2.2.0

---

frontend/automation/cypress/e2e/network-configuration.cy.js
frontend/automation/cypress/e2e/onboarding.cy.js

Fix failing regression test from last release and add implicit wait for flaky network switcher test

chore: fix failing CI test

---

CHANGELOG.md
backend/app_config.go
backend/handler.go
frontend/src/hooks/use-wallet-service.tsx

Clean up the application configuration if set with a non-existing network

---

CHANGELOG.md
backend/api_v2.go
backend/handler.go
build/darwin/Info.dev.plist
build/darwin/info.plist
os/init.go
os/notification/notify.go
os/notification/notify_darwin.go
os/notification/notify_darwin.h

Migrate MacOS notification to the UserNotification framework

---

CHANGELOG.md
backend/handler.go
backend/service_starter.go

Mark the service as not running when it failed to start

---

frontend/automation/cypress/e2e/network-configuration.cy.js
frontend/package.json
frontend/yarn.lock

fix: network switcher

---

frontend/package.json
frontend/src/index.tsx
frontend/yarn.lock

Closes #215 
Emil tested it, looks like it works now.
https://user-images.githubusercontent.com/105208209/220154854-b08544d9-72a9-4476-b1b1-3340a2cdd795.MOV

fix: add resize observer polyfill

---

CHANGELOG.md
backend/handler.go
backend/version.go
go.mod
go.sum

Implement the backend to pick up wallet updates made externally

---

CHANGELOG.md
backend/app_menu.go
backend/app_menu_common.go
backend/app_menu_darwin.go
frontend/package.json.md5

Add a "Help" menu

---

README.md

Update README with supported OSes

---

CHANGELOG.md
app/config.go

fix: add validation on vegahome path set in app-config

---

frontend/automation/e2e/onboarding.cy.ts

Some AC have been covered in previous PR, but without mentioning AC code.

chore: fill missing ac comment

---

frontend/automation/e2e/import-network.cy.ts
frontend/automation/e2e/import-wallet.cy.ts
frontend/automation/e2e/onboarding.cy.ts
frontend/automation/e2e/wallet-edit.cy.ts
frontend/automation/e2e/wallet-taint.cy.ts
frontend/automation/support/commands/restore-network.ts
frontend/automation/support/commands/restore-wallet.ts

chore: fix restore wallet function, add missing ac code

---

README.md
frontend/src/app.tsx

Change how fairground mode flag works

chore: change how fairground flag mode works

---

frontend/automation/e2e/import-network.cy.ts
frontend/src/app.tsx

Bang accidentally added by me. My bad.

chore: remove bad bangs

---

frontend/automation/e2e/onboarding.test.ts

This is a short term fix to unblock the failing tests on develop. Will follow this up with amended test cases based on environment variables.
https://github.com/vegaprotocol/vegawallet-desktop/issues/603

Fix failing import network test

---

frontend/package.json
frontend/yarn.lock

Bump UI to fix:
* Approval button enabled when it should not have been

chore: bump

---

CHANGELOG.md
backend/app_menu_common.go
go.sum

Add more shortcuts on the window to minimize the app

---

backend/service_starter.go
frontend/automation/e2e/wallet-annotate.test.ts
frontend/automation/e2e/wallet-taint.test.ts
frontend/automation/e2e/wallets-sign.test.ts
frontend/automation/e2e/wallets.test.ts
frontend/package.json
frontend/yarn.lock
go.mod
go.sum

Reduce the passphrase prompt occurence

---

app/config.go
backend/app_menu.go
frontend/src/hooks/use-wallet-client.tsx
frontend/src/hooks/use-wallet-service.tsx
main.go

Closes #523 
Enables vegaprotocol/vegawallet-ui#200
Enables https://github.com/vegaprotocol/vegawallet-ui/pull/207
Also:
* makes window a bit smaller to align with the compact design in wallet-ui

fix: show info when app settings are not saved
